### ISSUE TITLE
Auto-scale legend when using Bokeh

### ISSUE THREAD

**Issue by polklin** [perrin-isir/xomx#3]
Hello,

When using bokeh for plotting, there is no auto-scalling of the legend. 
For example, only a subset of my 81 labels are listed in the legend in the UMAP plot below:

![image](https://user-images.githubusercontent.com/25035705/179515038-21149915-0237-480f-b491-e4da20ba5464.png)

Bokeh does not provide an auto-scaling of the legend depending on the number of labels we are using (see open issues on git: https://github.com/bokeh/bokeh/issues/3880). But there are workarounds like [here](https://stackoverflow.com/questions/66716415/how-to-prevent-legend-being-truncated-in-bokeh).

Let me know what you think @perrin-isir, but ideally that would be nice to make all labels appear like this (from scanpy PCA plot):
![image](https://user-images.githubusercontent.com/25035705/179516205-fcf066e6-0809-4cd5-8297-9fb5530d8da4.png)

Best,
Paul

**Comment by perrin-isir** [comment]
Hi Paul, thanks for the feedback. I followed the workaround you suggested to solve the issue. It is a hacky solution, but it should work. Please tell me if you still observe some unexpected behavior.
Nicolas

**Comment by polklin** [comment]
![image](https://user-images.githubusercontent.com/25035705/180264749-2ff31764-eec8-4695-9150-ae37e16fd7ff.png)

Amazing thanks @perrin-isir !
